### GET request to example server
POST  http://127.0.0.1:8000/embed
Content-Type: application/json
Accept: application/json

{
    "text": "IMUNOFIXAÇÃO DE PROTEÍNAS EM URINA DE 24 HORAS; O principal objetivo das técnicas de imunofixação é definir o tipo de proteína anormal presente na amostra, identificando as cadeias envolvidas.Exame útil na detecção de cadeias Kappa livres e Lambda livre, indicativas da proteinúria de Bences-Jones."
}

###
